# Diagram reference: https://wokwi.com/projects/340062891526849108

[wokwi]
version = 1
gdbServerPort = 3333
elf = "target/xtensa-esp32s3-espidf/debug/hbee-plain-lcd"
firmware = "target/xtensa-esp32s3-espidf/debug/hbee-plain-lcd"
