
export struct SensorData {
    solution_temperature: float,
    has_solution_temperature: bool,
    electrical_conductivity: int,
    has_electrical_conductivity: bool,
    power_of_hydrogen: float,
    has_power_of_hydrogen: bool,
    electrical_resistivity: float,
    has_electrical_resistivity: bool,
    total_dissolved_solids: float,
    has_total_dissolved_solids: bool,
    solution_salinity: float,
    has_solution_salinity: bool,
}

export struct Health {
    gsm_signal_strength: int,
    has_gsm_signal_strength: bool,
    battery_level: int,
    has_battery_level: bool,
}
